# This config is meant to run the same training protocol as `first_try.yml`,
# but for more recent version of `atompaint`.

compute:
  train_cmd: ap_transform_pred
  memory_gb: 16

trainer:
  max_epochs: 1
  profiler: advanced

model:
  architecture: cnn
  frequencies: 2
  conv_channels: [4, 10, 20, 30, 40, 50]
  conv_field_of_view: [5, 3, 3, 3, 3]
  conv_stride: [2, 1, 1, 1, 1]
  conv_padding: 0
  mlp_channels: 1

data:
  origins_path: 20230708_origins_max_identity_30.0_max_resolution_3.0_min_nearby_atoms_25_radius_5.0
  grid_length_voxels: 21
  grid_resolution_A: 0.75
  element_channels: [C, N, O, .*]
  element_radii_A: 0.375  # grid_resolution_A / 2
  view_padding_A: 1.0
  batch_size: 16

  # ≈10 min/batch
  train_epoch_size: 32
  val_epoch_size: 0

  num_workers: 0
